### ISSUE TITLE
Forward strategy for Lua in RPM scriptlets

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1080]
Periodically we encounter issues because packagers have decided to use `lua` in their RPM scriptlets, which `rpm-ostree` doesn't currently support. This leads to a lot of confusion and unhappy campers on both ends, because there is nothing telling packagers they shouldn't use `lua` in RPM scriptlets. Here's the current situation:

- Currently `rpm-ostree` doesn't support `lua` in RPM scriptlets
    - https://github.com/coreos/rpm-ostree/issues/749
- When we encounter issues because of `lua` we have to ask the package maintainers to change their packages. If they refuse we have to [maintain a hacky and increasingly stale list of overrides for the `lua` scriptlets](https://github.com/coreos/rpm-ostree/blob/e063665538b2b37fadfe146c5d51c91577c7323b/src/libpriv/rpmostree-scripts.cxx#L117).
- An easy path towards supporting `lua` in RPM scriptlets is for `librpm` to provide an API for it, but doing that [has been refused](https://github.com/rpm-software-management/rpm/issues/1273#issuecomment-996519896) upstream

Given this information we either need to come up with other ideas for how to implement `lua` support for `rpm-ostree` or try to push forward with a Fedora Change Request that denies the use of `lua` in RPM scriptlets.

**Comment by dustymabe** [comment]
This was discussed briefly at the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/KWZOD327I54STWS2FCCNL6CN6IT7UA62/). There were no outcomes, just broad discussion that lead to opening this ticket.

**Comment by travier** [comment]
> try to push forward with a Fedora Change Request that denies the use of `lua` in RPM scriptlets.

I'm afraid that this will never be accepted as Lua scriptlets solves real issues for some packages (glibc, etc.).

However, I think we could ask for Lua scriplets to be only used for dnf specific (i.e. not applying to rpm-ostree based builds) config or state migration logic. Some Lua scripts would remain an exception (glibc, etc.) but most could then simply be ignored just fine.

**Comment by cverna** [comment]
Before doing a Fedora Change Request we could also just start the discussion on fedora-devel to get some early feedback.

**Comment by dustymabe** [comment]
another example of this hitting us: https://github.com/coreos/fedora-coreos-tracker/issues/1113

**Comment by lucab** [comment]
Recently we caught another one in https://github.com/coreos/rpm-ostree/issues/3418. In that case it wasn't actually required, so the package got directly fixed in `rawhide`.

**Comment by razum2um** [comment]
I was just interested how you guys do in the longterm and installed rawhide a year ago in a vm, almost didn't touch except chromium:

```
# rpm-ostree status
State: idle
Deployments:
  ostree://fedora:fedora/rawhide/x86_64/silverblue
                   Version: Rawhide.20210219.n.0 (2021-02-19T06:07:27Z)
                BaseCommit: 349fc427f6c0036f2c17c9de89d72e38b1de09d4232fb944ccd9d9e1eee51afe
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
           LayeredPackages: chromium

  ostree://fedora:fedora/rawhide/x86_64/silverblue
                   Version: Rawhide.20210219.n.0 (2021-02-19T06:07:27Z)
                    Commit: 349fc427f6c0036f2c17c9de89d72e38b1de09d4232fb944ccd9d9e1eee51afe
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
```

now tried to _just_ upgrade 🙂 idk if you find this feedback useful

```
# error like
# error: While pulling fedora/rawhide/x86_64/silverblue: Commit 0a9c3709cbbf37e4c078bf519b92e4bfbd02cb12ad18542078fff2eabcf78896: Signature made Sun 22 May 2022 09:03:33 AM MSK using RSA key ID F55AD3FB5323552A
# fixed like that:
cd /etc/pki/rpm-gpg
wget https://src.fedoraproject.org/rpms/fedora-repos/raw/rawhide/f/RPM-GPG-KEY-fedora-37-primary
ostree remote gpg-import fedora -k RPM-GPG-KEY-fedora-37-primary
```

but `rpm-ostree upgrade` still fails like that:

```
2 metadata, 0 content objects fetched; 788 B transferred in 2 seconds; 0 bytes content written
Checking out tree 0a9c370... done
Enabled rpm-md repositories: fedora-cisco-openh264 rawhide
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2022-04-07T16:52:38Z
rpm-md repo 'rawhide' (cached); generated: 2022-05-22T07:38:55Z
Importing rpm-md... done
Resolving dependencies... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
error: Executing %transfiletriggerin for glibc-common: Package 'glibc-common' has (currently) unsupported <lua> script in '%transfiletriggerin'
```

I've read the thread and related stuff: do I understand correctly that 
1. this is basically a dead end, I can only install from scratch
1. it will repeat after each glibc upgrade?

**Comment by travier** [comment]
This is the issue tracker for Fedora CoreOS not Fedora Silverblue. Please file an issue there: https://github.com/fedora-silverblue/issue-tracker/issues

**Comment by dustymabe** [comment]
- https://github.com/coreos/rpm-ostree/pull/3909

**Comment by cgwalters** [comment]
This is now lower priority as we'll be emphasizing customization via containers using https://fedoraproject.org/wiki/Changes/OstreeNativeContainerStable and hence we are again running lua scripts today in the same way traditional dnf does.
